# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(809, 690)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.selectExpensesAccountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectExpensesAccountBtn.setObjectName("selectExpensesAccountBtn")
        self.gridLayout.addWidget(self.selectExpensesAccountBtn, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.selectCurrencyBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectCurrencyBtn.setObjectName("selectCurrencyBtn")
        self.gridLayout.addWidget(self.selectCurrencyBtn, 2, 2, 1, 1)
        self.defaultCurrencyLE = QtWidgets.QLineEdit(self.centralwidget)
        self.defaultCurrencyLE.setObjectName("defaultCurrencyLE")
        self.gridLayout.addWidget(self.defaultCurrencyLE, 2, 1, 1, 1)
        self.transactionTableView = QtWidgets.QTableView(self.centralwidget)
        self.transactionTableView.setObjectName("transactionTableView")
        self.gridLayout.addWidget(self.transactionTableView, 4, 0, 1, 3)
        self.defaultExpensesAccountLE = QtWidgets.QLineEdit(self.centralwidget)
        self.defaultExpensesAccountLE.setObjectName("defaultExpensesAccountLE")
        self.gridLayout.addWidget(self.defaultExpensesAccountLE, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.defaultPaymentAccountLE = QtWidgets.QLineEdit(self.centralwidget)
        self.defaultPaymentAccountLE.setObjectName("defaultPaymentAccountLE")
        self.gridLayout.addWidget(self.defaultPaymentAccountLE, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.selectPaymentAccountBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectPaymentAccountBtn.setObjectName("selectPaymentAccountBtn")
        self.gridLayout.addWidget(self.selectPaymentAccountBtn, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 809, 23))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openAlipayCsvAction = QtWidgets.QAction(MainWindow)
        self.openAlipayCsvAction.setObjectName("openAlipayCsvAction")
        self.openBeancountAccountAction = QtWidgets.QAction(MainWindow)
        self.openBeancountAccountAction.setObjectName("openBeancountAccountAction")
        self.openWechatCsvAction = QtWidgets.QAction(MainWindow)
        self.openWechatCsvAction.setObjectName("openWechatCsvAction")
        self.menuFiles.addAction(self.openBeancountAccountAction)
        self.menuFiles.addAction(self.openAlipayCsvAction)
        self.menuFiles.addAction(self.openWechatCsvAction)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beancount importer"))
        self.selectExpensesAccountBtn.setText(_translate("MainWindow", "Select"))
        self.label_3.setText(_translate("MainWindow", "Default currency"))
        self.selectCurrencyBtn.setText(_translate("MainWindow", "Select"))
        self.label_2.setText(_translate("MainWindow", "Default expenses account"))
        self.label.setText(_translate("MainWindow", "Default payment account"))
        self.selectPaymentAccountBtn.setText(_translate("MainWindow", "Select"))
        self.label_4.setText(_translate("MainWindow", "Transactions"))
        self.menuFiles.setTitle(_translate("MainWindow", "File"))
        self.openAlipayCsvAction.setText(_translate("MainWindow", "Open Alipay csv"))
        self.openBeancountAccountAction.setText(_translate("MainWindow", "Open beancount account"))
        self.openWechatCsvAction.setText(_translate("MainWindow", "Open Wechat csv"))
