# Form implementation generated from reading ui file 'account_map_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AccountMapDialog(object):
    def setupUi(self, AccountMapDialog):
        AccountMapDialog.setObjectName("AccountMapDialog")
        AccountMapDialog.resize(387, 531)
        self.verticalLayout = QtWidgets.QVBoxLayout(AccountMapDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mapTypeLabel = QtWidgets.QLabel(AccountMapDialog)
        self.mapTypeLabel.setObjectName("mapTypeLabel")
        self.verticalLayout.addWidget(self.mapTypeLabel)
        self.accountMapTableWidget = QtWidgets.QTableWidget(AccountMapDialog)
        self.accountMapTableWidget.setObjectName("accountMapTableWidget")
        self.accountMapTableWidget.setColumnCount(0)
        self.accountMapTableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.accountMapTableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addRowBtn = QtWidgets.QPushButton(AccountMapDialog)
        self.addRowBtn.setObjectName("addRowBtn")
        self.horizontalLayout.addWidget(self.addRowBtn)
        self.deleteRowBtn = QtWidgets.QPushButton(AccountMapDialog)
        self.deleteRowBtn.setObjectName("deleteRowBtn")
        self.horizontalLayout.addWidget(self.deleteRowBtn)
        self.okBtn = QtWidgets.QPushButton(AccountMapDialog)
        self.okBtn.setObjectName("okBtn")
        self.horizontalLayout.addWidget(self.okBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AccountMapDialog)
        self.okBtn.clicked.connect(AccountMapDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AccountMapDialog)

    def retranslateUi(self, AccountMapDialog):
        _translate = QtCore.QCoreApplication.translate
        AccountMapDialog.setWindowTitle(_translate("AccountMapDialog", "Account Map"))
        self.mapTypeLabel.setText(_translate("AccountMapDialog", "Map type"))
        self.addRowBtn.setText(_translate("AccountMapDialog", "Add row"))
        self.deleteRowBtn.setText(_translate("AccountMapDialog", "Delete row"))
        self.okBtn.setText(_translate("AccountMapDialog", "OK"))
